# These are supported funding model platforms

github: "https://github.com/Guga-innecco"
patreon: ""
open_collective: ""
ko_fi: ""
tidelift: ""
community_bridge: "ReactLite"
liberapay: ""
issuehunt: ""
otechie: ""
custom: ""
