# These are supported funding model platforms

github: "https://github.com/Guga-innecco"
patreon: no
open_collective: no
ko_fi: no
tidelift: no
community_bridge: "ReactLite"
liberapay: "React"
issuehunt: no
otechie: no
custom: no
